mod day1;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;

fn main() {
    // println!("Day 1");
    // day1::solve();
    // println!("Day 2");
    // day2::solve();
    // println!("Day 3");
    // day3::solve();
    // println!("Day 4");
    // day4::solve();
    // println!("Day 5");
    // day5::solve();
    // println!("Day 6");
    // day6::solve();
    // println!("Day 7");
    // day7::solve();
    // println!("Day 8");
    // day8::solve();
    // println!("Day 9");
    // day9::solve();
    // println!("Day 10");
    // day10::solve();
    // println!("Day 11");
    // day11::solve();
    // println!("Day 12");
    // day12::solve();
    // println!("Day 13");
    // day13::solve();
    println!("Day 14");
    day14::solve();
}
